### ISSUE TITLE
Installation instructions don't mention CLJ_CONFIG or XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by schaueho** [practicalli/clojure-deps-edn#10]
After following the installation instructions, calling any of the provided aliases failed with the error message "No function found on command line or in :exec-fn". Due to the help of Alex Miller and Sean Corfield on the Clojurians Slack channel, it became clear that the issue is that after installing the Clojure CLI tools, my config-user is not pointing to `$HOME/.clojure` but to `$HOME/.config/clojure`. I.e., see the output of `clojure -Sdescribe`: 

```
[host->~]clojure -Sdescribe
{:version "1.10.1.727"
 :config-files ["/usr/local/lib/clojure/deps.edn" "/home/schauer/.config/clojure/deps.edn" ]
 :config-user "/home/schaueho/.config/clojure/deps.edn"
 :config-project "deps.edn"
 :install-dir "/usr/local/lib/clojure"
 :config-dir "/home/schaueho/.config/clojure"
 :cache-dir "/home/schaueho/.config/clojure/.cpcache"
 :force false
 :repro false
 :main-aliases ""
 :repl-aliases ""}
```

According to Alex, the reason is in my case that the environment variable `$XDG_CONFIG_HOME` points to `/home/schaueho/`. Apparently, setting $CLJ_CONFIG could lead to similar effects, as described in [deps and cli documentation](https://clojure.org/reference/deps_and_cli#_deps_edn_sources).

My proposal would be to change the documentation so that instead of just assuming `~/.clojure/` to specifically mention the value of `:config-user` from the output above.

**Comment by jr0cket** [comment]
Thank you for sharing your experience.  I am also curious to why there is a different value for the location of Clojure config.

Do you know if the setting was defined by a specific operating system, if so can you share which one.

Maybe this was set by an application or shell tool.  Or was this set manually.

I do think $HOME/.config/clojure is a more modern location, rather than putting it in the root of the home account.

I have not seen much discussion about $CLJ_CONFIG so will have a look into what that is doing and try understand why it would be set.

**Comment by schaueho** [comment]
I didn't set XDG_CONFIG_HOME myself anywhere. The system I encountered this on is using Debian Buster. Debian is pushing to follow the so-called XDB Base Directory specification, more details can be found in the [Debian wiki page on XDGBaseDirectorySpecification](https://wiki.debian.org/XDGBaseDirectorySpecification).
My guess would be that this highly likely also applies to Debian derivatives such as Ubuntu.

**Comment by jr0cket** [comment]
Thank you, that is really helpful to know.  I will make some changes today.
