### ISSUE TITLE
No function found on command line or in :exec-fn on new project

### ISSUE THREAD

**Issue by chrysophylax** [practicalli/clojure-deps-edn#17]
I run the new project template and it flunks. 
```
user$ clojure -X:project/new :template app :name practicalli/testapp
No function found on command line or in :exec-fn
```

Here's the output of `clojure -Sdescribe`
```
{:version "1.10.1.763"
 :config-files ["/usr/share/clojure/deps.edn" "/home/billy/.clojure/deps.edn" ]
 :config-user "/home/billy/.clojure/deps.edn"
 :config-project "deps.edn"
 :install-dir "/usr/share/clojure"
 :config-dir "/home/billy/.clojure"
 :cache-dir "/home/billy/.clojure/.cpcache"
 :force false
 :repro false
 :main-aliases ""
 :repl-aliases ""}
```

**Comment by jr0cket** [comment]
I cannot reproduce the error reported I am afraid.

Suggest removing the :cache-dir and trying again, especially if you have updated the version of the Clojure CLI tools recently.

Otherwise, check for changes in the deps.edn file since cloning the project.  If you can share the deps.edn file that is your :config-user then I can also check if there are differences.

**Comment by chrysophylax** [comment]
Yeah, I think we can close this. I upgraded my tools at some point during the weekend and now I can't repro either. Weird. Thanks anyway for the suggestions.
